export default {
    editor: {
        base: 'vs',
        rules: [
            {background: '#ffffff'},
            {token: 'keywords', foreground: '000080', fontStyle: 'bold'},
            {token: 'number', foreground: '0000FF'},
            {token: 'keyword', foreground: '000080', fontStyle: 'bold'},
            {token: 'string.sql', foreground: '008000'},
            {token: 'tag.sql', foreground: '0033B3'},
            {token: 'attribute.name.sql', foreground: '174AD4'},
            {token: 'attribute.value.sql', foreground: '067D17'},
            {token: 'predefined', foreground: '000000', fontStyle: 'italic'},
            {token: 'operator.sql', foreground: '000080', fontStyle: 'bold'},
            {token: 'key', foreground: '660E7A'},
            {token: 'string.key.json', foreground: '660E7A'},
            {token: 'string.value.json', foreground: '008000'},
            {token: 'keyword.json', foreground: '0000FF'},
            {token: 'string', foreground: '008000', fontStyle: 'bold'},
            {token: 'string.invalid', foreground: '008000', background: 'FFCCCC'},
            {token: 'string.escape.invalid', foreground: '008000', background: 'FFCCCC'},
            {token: 'string.escape', foreground: '000080', fontStyle: 'bold'},
            {token: 'comment', foreground: '808080', fontStyle: 'italic'},
            {token: 'comment.doc', foreground: '808080', fontStyle: 'italic'},
            {token: 'comment.todo', foreground: '008DDE', fontStyle: 'italic'},
            {token: 'string.escape', foreground: '000080'}
        ],
        colors: {
            'editor.foreground': '#000000',
            'editor.background': '#ffffff',
            'editorLineNumber.foreground': '#999999',	//行号的颜色
            'editorGutter.background': '#f0f0f0',	//行号背景色
            'editor.lineHighlightBackground': '#FFFAE3',	//光标所在行的颜色
            'dropdown.background': '#F2F2F2',	//右键菜单
            'dropdown.foreground': '#000000',	//右键菜单文字颜色
            'list.activeSelectionBackground': '#1A7DC4',	//右键菜单悬浮背景色
            'list.activeSelectionForeground': '#ffffff',	//右键菜单悬浮文字颜色
        }
    },
    styles: {
        'color': '#000',
        'empty-color': '#505050',
        'empty-key-color': '#5263A0',
        'background': '#f2f2f2',
        'empty-background': '#B6B6B6',
        'border-color': '#cdcdcd',
        'input-border-color': '#bdbdbd',
        'input-border-foucs-color': '#0784DE',
        'input-background': '#fff',
        'select-border-color': '#808080',
        'select-background': '#e3e3e3',
        'select-icon-background': '#fff',
        'select-option-background': '#fff',
        'select-hover-background': '#e3f1fa',
        'select-option-hover-background': '#1A7DC4',
        'select-option-hover-color': '#fff',
        'select-option-disabled-color': '#c0c4cc',
        'select-inputable-background': '#fff',
        'select-inputable-border': '#bdbdbd',
        'checkbox-background': '#fff',
        'checkbox-text-color': '#fff',
        'checkbox-border': '#b0b0b0',
        'checkbox-selected-border': '#4F9EE3',
        'checkbox-selected-background': '#4F9EE3',
        'header-title-color': '#000',
        'header-version-color': '#333',
        'header-default-color': '#6e6e6e',
        'dialog-button-hover-border-color': '#99a0a5',
        'dialog-button-hover-background': '#E3F1FA',
        'dialog-button-background': '#E3E3E3',
        'dialog-button-border': '#ADADAD',
        'dialog-border-color': '#707070',
        'dialog-shadow-color': '#cfcfcf',
        'middle-background': '#F0F0F0',
        'button-run-color': '#59A869',
        'button-hover-background': '#d9d9d9',
        'button-disabled-background': '#BDBDBD',
        'toolbox-border-right-color': '#c0c0c0',
        'toolbox-border-color': '#c9c9c9',
        'icon-color': '#6e6e6e',
        'icon-debug-color': '#59A869',
        'icon-step-color': '#389FD6',
        'selected-background': '#bdbdbd',
        'hover-background': '#d9d9d9',
        'toolbox-list-hover-background': '#d4d4d4',
        'toolbox-background': '#fff',
        'toolbox-list-selected-background': '#d4d4d4',
        'toolbox-list-icon-color': '#aeb9c0',
        'toolbox-list-span-color': '#999',
        'toolbox-list-label-color': '#000',
        'toolbox-list-arrow-color': '#b3b3b3',
        'toolbox-list-header-icon-color': '#7f7f7f',
        'tab-bar-border-color': '#c9c9c9',
        'footer-border-color': '#919191',
        'table-col-border-color': '#e5e5e5',
        'table-row-border-color': '#c0c0c0',
        'table-even-background': '#F2F5F9',
        'table-hover-color': '#fff',
        'table-hover-background': '#1A7DC4',
        'breakpoints-background': '#db5860',
        'debug-line-background': '#2154A6',
        'breakpoint-line-background': '#FAEAE6',
        'todo-color': '#008DDE',
        'history-select-background': '#1A7DC4',
        'history-select-color': '#fff',
        'text-number-color': '#0000FF',
        'text-string-color': '#008000',
        'text-boolean-color': '#000080',
        'text-default-color': '#000000',
        'text-key-color': '#660e7a',
        'suggest-hover-background': '#D6EBFF',
        'suggest-hover-color': '#000',
        'statusbar-em-color': '#007f31',
        'run-log-background': '#fff',
        'log-level-info': '#00cd00',
        'log-level-warn': '#A66F00',
        'log-level-debug': '#00cccc',
        'log-level-error': '#cd0000',
        'log-level-trace': '#0000EE',
        'log-color-cyan': '#00CCCC',
        'log-color-link': '#006DCC',
    }
};